### ISSUE TITLE
unable to run import or export properly due to terraform --version error

### ISSUE THREAD

**Issue by dp80** [databrickslabs/databricks-sync#60]
I have following version installed

Teraform 0.14.9 version
tfenv 2.2.0

`2021-03-29 23:30:12 [INFO] command: terraform --version
2021-03-29 23:30:13 [ERROR] cat: /root/.tfenv/version: No such file or directory
2021-03-29 23:30:13 [ERROR] Version could not be resolved (set by /root/.tfenv/version or tfenv use <version>)
Traceback (most recent call last):
  File "/usr/local/bin/databricks-sync", line 8, in <module>
    sys.exit(cli())
`

actual path to the terraform version:  /root/.tfenv/versions/0.14.9

**Comment by dp80** [comment]
I am able to get around this error by running this command before the import/export command.

`tfenv use 0.14.9`

**Comment by stikkireddy** [comment]
@dp80 we will soon be uploading this tool as a databricks notebook to make it easier to execute this tool to avoid any of these dependency type issues.

**Comment by R7L208** [comment]
Thanks for raising this! In addition to @stikkireddy's comment, steps to resolve this are documented [here](https://github.com/databrickslabs/databricks-sync/blob/master/docs/setup.md#terraform).

We will be creating a FAQ and will include this error.

Closing since this since it is resolved by running `tfenv use`.
